[package]
name = "dynamic"
version = "4.2.0"
authors = ["Peter Dong"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "peter_lib"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
